FROM amazoncorretto:21-alpine-jdk
WORKDIR /app

# 프로젝트 파일 복사
COPY . .

# Gradle Wrapper에 실행 권한 부여
RUN chmod +x ./gradlew

# Gradle 빌드 실행 및 결과 확인
RUN ./gradlew build --no-daemon && \
    ls -l build/libs/

# JAR 파일 실행
EXPOSE 8080
CMD ["java", "-jar", "build/libs/webtoon-search-0.0.1-SNAPSHOT.jar"]
